V_Grafo/FrontG/app.py
from flask import Flask

def create_app():
    app = Flask(__name__, instance_relative_config=False)
    with app.app_context():
        from routes.router import router
        app.register_blueprint(router)
    return app

V_Grafo/FrontG/routes/router.py
from flask import Flask, json, flash, Blueprint, url_for, jsonify, make_response, request, render_template, redirect, abort
import requests
from urllib.parse import quote

router = Blueprint('router', __name__)

@router.route('/admin')
def admin():
    return render_template('tmpl/lista.html')

@router.route('/grafo')
def grafo():
    return render_template("tmpl/grafo.html")

@router.route('/admin/universidad/list')
def list_sintetica():
    r = requests.get("http://localhost:8075/api/universidad/list")
    data = r.json()
    return render_template('tmpl/lista.html', list=data["data"])

@router.route('/admin/universidad/edit/<int:id>')
def view_edit_sintetica(id):
    r = requests.get("http://localhost:8075/api/universidad/list")
    data = r.json()
    r1 = requests.get(f"http://localhost:8075/api/universidad/get/{id}")
    data1 = r1.json()
    
    if r1.status_code == 200:
        return render_template('tmpl/editar.html', list=data["data"], sintetica=data1["data"])
    else:
        flash("sintetica no encontrado", category='error')
        return redirect("/admin/universidad/list")

@router.route('/admin/universidad/register')
def view_register_sintetica():
    r = requests.get("http://localhost:8075/api/universidad/list")
    data = r.json()
    return render_template('tmpl/registro.html', list=data["data"])

@router.route('/admin/universidad/save', methods=["POST"])
def save_sintetica():
    headers = {'Content-type': 'application/json'}
    form = request.form
    print("Datos del formulario:", form)
    try:
        dataF = {
            "nombre": form["nombre"],
            "latitud": float(form["latitud"]),
            "longitud": float(form["longitud"]),
            "tipo": form["tipo"],
        }
        print("Datos enviados al backend:", dataF) 
        r = requests.post("http://localhost:8075/api/universidad/save", data=json.dumps(dataF), headers=headers)
        dat = r.json()
        print("Respuesta de la API:", dat)
        if r.status_code == 200:
            flash("Sintética guardada correctamente", category='info')
        else:
            flash("Error al guardar la sintética", category='error')

    except ValueError:
        flash("Error: La latitud y longitud deben ser valores numéricos", category='error')

    return redirect(url_for("router.list_sintetica"))


@router.route('/admin/universidad/delete/<int:id>', methods=['DELETE'])
def delete_sintetica(id):
    try:
        response = requests.delete(f"http://localhost:8075/api/universidad/delete/{id}")
        if response.status_code == 200:
            flash("sintetica eliminado exitosamente", "info")
            return jsonify({"message": "sintetica eliminado exitosamente."}), 200  # Responder con JSON
        else:
            flash("Error al eliminar el sintetica.", "danger")
            return jsonify({"error": "No se pudo eliminar el sintetica."}), response.status_code
    except Exception as e:
        flash(f"Hubo un error: {str(e)}", "danger")
        return jsonify({"error": str(e)}), 500  


@router.route('/admin/universidad/update', methods=["POST"])
def update_sintetica():
    headers = {'Content-type': 'application/json'}
    form = request.form
    dataF = {
        "idSintetica": form["id"],
        "nombre": form["nombre"],
            "latitud": float(form["latitud"]),
            "longitud": float(form["longitud"]), 
            "tipo": form["tipo"],
    }
    r = requests.post("http://localhost:8075/api/universidad/update", data=json.dumps(dataF), headers=headers)
    dat = r.json()
    
    if r.status_code == 200:
        flash("sintetica actualizado correctamente", category='info')
       
    else:
        flash(str(dat["data"]), category='error')

    return redirect("/admin/universidad/list")

V_Grafo/FrontG/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Grafos</title>

  <!-- Main CSS File -->
  <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
  <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
</head>

<body class="index-page">
    <i class="header-toggle d-xl-none bi bi-list" aria-label="Toggle Navigation Menu"></i>
    
    <nav id="navmenu" class="navmenu">
        <li><a href="/admin/universidad/list"><i class="bi bi-file-earmark-text navicon"></i> Universidades</a></li>
        <li><a href="/admin/universidad/register"><i class="bi bi-images navicon"></i>Registrar Universidad</a></li>
        <li><a href="/grafo"><i class="bi bi-images navicon"></i> Grafo </a></li>
    </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <main class="main">

  </main>
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
        
  <!-- Main JS File -->
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
</body>
</html>
</body>
</html>

V_Grafo/FrontG/templates/tmpl/editar.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
  <div class="pagetitle text-center">
    <h1 class="text-black">Editar Datos </h1> 
  </div>
  
  <section class="section">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-white">Actualizar datos </h5>
            <form class="row g-3 needs-validation" method="POST" action="/admin/universidad/update" novalidate>
                <input type="hidden" value="{{sintetica.idSintetica }}" name="id" />
                <div class="mb-3">
                  <label for="nombre" class="form-label text-black">Nombre</label>
                  <input type="text" class="form-control" name="nombre" required value="{{ sintetica.nombre }}">
                </div>
                <div class="mb-3">
                  <label for="latitud" class="form-label text-black">Ltd</label>
                  <input type="Double" class="form-control" name="latitud" required value="{{ sintetica.latitud }}">
                </div>
                <div class="mb-3">
                  <label for="longitud" class="form-label text-black">Lng</label>
                  <input type="text" class="form-control" name="longitud" required value="{{ sintetica.longitud}}">
                </div>
                <div class="mb-3">
                  <label for="tipo" class="form-label text-black">Tipo</label>
                  <input type="text" class="form-control" name="tipo" required>
                </div>
                <a href="/admin/inversionista/list" class="btn btn-custom btn-secondary">Cancelar</a>
                <button type="submit" class="btn btn-custom btn-primary">Guardar</button> <!-- Estilo de botón personalizado -->
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<script>
  document.querySelectorAll('#star-rating .star').forEach(star => {
      star.addEventListener('click', function() {
          let value = this.getAttribute('data-value');
          let select = document.querySelector('#star-rating select');
          select.value = value;
          document.querySelectorAll('#star-rating .star').forEach(innerStar => {
              if (innerStar.getAttribute('data-value') <= value) {
                  innerStar.classList.add('selected');
              } else {
                  innerStar.classList.remove('selected');
              }
          });
      });
  });
</script>

{% endblock %}

V_Grafo/FrontG/templates/tmpl/grafo.html
<!DOCTYPE html>
<html lang="en-US">
<head>
<script src="../static/js/vis.js"></script>
<style type="text/css">
      #mynetwork {
    width: 800px;  /* Asegúrate de que sea lo suficientemente grande */
    height: 600px;
    border: 1px solid lightgray;
}

    </style>
</head>
<body>

<div class="header">
  <p>Muestra el grafo</p>
</div>

  <div id="mynetwork"></div>
  
  <script type="text/javascript" src="../static/js/graph.js"></script>
</body>
</html>

V_Grafo/FrontG/templates/tmpl/lista.html
{% extends 'index.html' %}

{% block content %}
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
<!-- Quill.js CSS -->
<link href="https://cdn.quilljs.com/1.3.7/quill.snow.css" rel="stylesheet">

<!-- Quill.js JavaScript -->
<script src="https://cdn.quilljs.com/1.3.7/quill.min.js"></script>

</script>
<div class="pagetitle">
    <h1>Universidades</h1>
</div>

<div class="col-12">
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th> Latitud</th>
                <th> Longitud </th>
                 <th>Tipo</th>
               
            </tr>
        </thead>
        <tbody>
            {% if list %}
                {% for item in list %}
                <tr id="row-{{ item.idSintetica }}">
                    <td>{{ item.nombre }}</td>
                    <td>{{ item.latitud }}</td>
                    <td>{{ item.longitud }}</td>
                    <td>{{ item.tipo }}</td>
                    <td>
                        <a href="/admin/universidad/edit/{{ item.idUniversidad }}" class="btn btn-info">Modificar</a>
                        <button class="btn btn-danger" onclick="deleteRow({{ item.idUniversidad }})">Eliminar</button>
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="11">No hay proyectos registrados.</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>

<script>
    function deleteRow(id) {
        const row = document.getElementById(`row-${id}`);
        if (confirm("¿Continuar?")) {
            row.remove();
        }
    }
</script>

{% endblock %}

V_Grafo/FrontG/templates/tmpl/registro.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
  <div class="pagetitle text-center">
    <h1 class="text-black">Agregar universidad</h1>
  </div>
  
  <section class="section">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-white">Ingresa los datos del sintetica</h5>

            <form class="row g-3 needs-validation" method="POST" action="{{ url_for('router.save_sintetica') }}" novalidate>

              <div class="mb-3">
                <label for="nombre" class="form-label text-black">Nombre</label>
                <input type="text" class="form-control" name="nombre" required>
              </div>
              <div class="mb-3">
                <label for="nombre" class="form-label text-black">Tipo</label>
                <input type="text" class="form-control" name="tipo" required>
              </div>        
              <div class="mb-3">
                <label for="latitud" class="form-label text-black">Latitud</label>
                <input type="number" class="form-control" name="latitud" step="0.0000001" id="latitud" required>
              </div>
              <div class="mb-3">
                <label for="longitud" class="form-label text-black">Longitud</label>
                <input type="number" class="form-control" name="longitud" step="0.0000001" id="longitud" required>
              </div>
              <div class="d-flex justify-content-between mt-3">
                <button type="submit" class="btn btn-custom btn-light">Guardar</button>
                <a href="/admin/universidad/list" class="btn btn-custom btn-secondary">Cancelar</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<style>
  .pagetitle {
    margin-bottom: 20px;
  }

  .text-black {
    color: #000; /* Color negro para el encabezado y etiquetas */
  }

  .text-white {
    color: #fff; /* Color blanco para otros textos */
  }

  .btn-custom {
    font-size: 14px;
    color: #fff;
    border-radius: 5px;
    padding: 8px 16px;
    transition: background-color 0.3s ease;
  }

  .btn-custom.btn-light {
    background-color: #f8f9fa; /* Color claro para el botón "Guardar" */
    color: #000; /* Texto en negro */
  }

  .btn-custom.btn-secondary {
    background-color: #6c757d; /* Color gris para el botón "Cancelar" */
  }

  .btn-custom.btn-light:hover {
    background-color: #e2e6ea; /* Color de fondo al pasar el mouse */
  }

  .btn-custom.btn-secondary:hover {
    background-color: #5a6268; /* Color de fondo al pasar el mouse */
  }

  .map-container {
    width: 100%;
    display: flex;
    justify-content: center;
    margin-top: 10px;
  }

  #map {
    width: 200%;
    height: 300px; /* Tamaño pequeño del mapa */
    max-width: 500px; /* Controla el ancho del mapa */
    border: 1px solid #ccc;
    border-radius: 5px;
  }
</style>
{% endblock %}